@startuml

class Souerce
class Proxyobj
interface Sourceable

Souerce..|>Sourceable
Proxyobj..|>Sourceable
Proxyobj..>Souerce
Souerce : +method1()
Proxyobj : +method1()
Proxyobj : Proxyobj()
Proxyobj : -Souerce souerce
Sourceable : +method1()

@enduml